config/routes.rb
Musicapp::Application.routes.draw do
   resources :users
   resource :session, only:[:new, :create, :destroy]
   resources :likes

end

app/models/like.rb
class Like
	include Mongoid::Document
	field :text, type: String

	belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :name, type: String
  field :email, type: String 
  field :location, type: String
  field :password_digest, type: String

  has_many :likes	

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user 
  	@current_user ||= User.where(:id => session[:user_id]).first 
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  	@likes = Like.all
  end

  def new
  	@like = Like.new
  end

  def create
  	like = Like.new(
  		params.require(:like).permit(:text, :user_id)
  		)
  	if like.save
	  	redirect_to likes_path
  	end
  end

  def destroy
  	Like.find(params[:id]).destroy
  	redirect_to likes_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		# Present an empty login form
		@user = User.new
		@is_login = true
	end

	def create
		# Find the user that is trying to log in		
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			# Store as a cookie in the users' browser the ID of them,
			# indicating that they are logged in
			session[:user_id] = u.id.to_s
			redirect_to likes_path
		else
			# Go back to the login page
			redirect_to new_session_path
		end
	end

	def destroy
		reset_session
		redirect_to new_session_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end	

	def show
		# @user = Show.find(params[:id])
	end

	def new
		@user = User.new
		@is_signup = true
	end

	def create
		@user = User.new(params.require(:user).permit(:name, :email, :location, :password, :password_confirmation))
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to likes_path
		else
			redirect_to new_user_path
		end
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to users_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% if current_user %>
Welcome <%= current_user.name %>
<%= link_to "Logout", session_path, method: :delete %>
<% else %>
<%= link_to "Signup", new_user_path if !@is_signup%>

<%= link_to "Login", new_session_path if !@is_login%>


<% end %>

</body>
</html>

app/views/likes/index.html.erb
<h1>Likes</h1>
<ul>
<% @likes.each do |l| %>
	<li>
		User: <%= link_to l.text %>  
	</li>
	<li>
		<%= button_to "X", user_path(u.id), method: :delete %>
	</li>
<% end %>
</ul>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
<% @users.each do |u| %>
	<li>
		User: <%= link_to u.name %>  
	</li>
	<li>
		From: <%= link_to u.location %>
		<%= button_to "X", user_path(u.id), method: :delete %>
	</li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up here</h1>

<%= form_for @user do |f| %>
<%= f.text_field :name, placeholder:"Name" %>
<%= f.text_field :email, placeholder:"Email" %>
<%= f.text_field :location, placeholder:"Where do you live" %>
<%= f.password_field :password, placeholder:"Enter Password" %>
<%= f.password_field :password_confirmation, placeholder:"Confirm Password" %>

<%= f.submit "Sign up!" %>

<% end %>